<a href="https://colab.research.google.com/github/yesung05/Deep-Learning-Study/blob/main/w04_3_python_numpy_function2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# SECTION 3 내장함수 zeros()와 ones(), empty()

## 원소가 모두 0인 배열을 생성하는 zeros()

In [ ]:
import numpy as np
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this arg

In [ ]:
import numpy as np

a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [ ]:
a.dtype #datatype


dtype('float64')

In [ ]:
np.zeros((5,),dtype=int) #그냥 (5,)는 열이 5개짜리 생성

array([0, 0, 0, 0, 0])

In [ ]:
b = np.zeros((2,1))
b

array([[0.],
       [0.]])

In [ ]:
b.shape

(2, 1)

## 원소가 모두 1인 배열을 생성하는 ones()

In [ ]:
import numpy as np

np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
import numpy as np

np.ones((2,4), dtype=int) # 기본은 실수형임 #이것도 뭔가 O,X 느낌? np.ones로 생성한 배열의 기본 자료형은 int이다 (O, X)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

## 대각선 원소가 모두 1인 2차원 배열을 생성하는 eye()

In [ ]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__ar

In [ ]:
import numpy as np

np.eye(3) #단위행렬? 예도 기본 float

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
np.eye(3,4) #가로 새로가 다르면 왼쪽 위 고정

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
a = np.eye(3,4,1) #행, 열, 1시작 지점

In [ ]:
a = np.eye(3,4,-1)

## 원소가 모두 1인 배열을 생성하는 full()

In [ ]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar or array_like
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         ``np.array(fill_value).dtype``.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible wit

In [ ]:
import numpy as np

np.full([2,3],10) #(행, 열)을 10으로 채워라

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
np.full([2,3],(1,2,3)) #1,2,3 이 들어간 2x3 배열

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
np.full([3,4], range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
np.full([4,3],fill_value=np.arange(4).reshape(4,1))
# full로 4x3배열 만들기, fill_value= 는 여기서는 필요 없을수도? 변수는 아님. 1x2 배열 생성[[0][1][2][3]] -> reshape 없으면 오류 발생 왜? => 3열인데 4개의 데이터 넣으려 함. arange(3) 이면 오류는 없음 다만 012 012 이런싟
#뭔가 리스트 컨프리헨션처럼 햇갈리는게 있을듯.

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

## 원소가 모두 1인 배열을 생성하는 empty()

In [ ]:
import numpy as np

np.empty([2,2])

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [ ]:
np.empty(3)

array([4.9e-324, 9.9e-324, 1.5e-323])

In [ ]:
np.empty([2,3], dtype=int)

array([[135465536657692,               0, 135458974486848],
       [135458974487040, 135458974487168, 135458974487296]])

## 원소값이 0인 주어진 형태의 배열을 생성하는 zeros_like()

In [ ]:
import numpy as np

a = np.arange(8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
np.zeros_like(a) # 기존 행렬과 같은 형태이지만 내용물이 0임

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

## 원소값이 1인 주어진 형태의 배열을 생성하는 ones_like()

In [ ]:
np.ones_like(a) #책에선 실수인데 여기선 정수? 책이 오류인가 내가 실수했나.

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

## 원소값이 주어진 값이며 주어진 형태의 배열을 생성하는 full_like()

In [ ]:
np.full_like(a,5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])